services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: mern-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: mernapp
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mern-network

  # Backend Service
  backend:
    build:
      context: .  # Contexte à la racine car package.json y est
      dockerfile: backend/Dockerfile
    container_name: mern-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGO_URI: mongodb://mongodb:27017/mernapp
      JWT_SECRET: abc123
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - mern-network

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mern-frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:5000
      CHOKIDAR_USEPOLLING: true
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mern-network

volumes:
  mongodb_data:

networks:
  mern-network:
    driver: bridge